spring:
  datasource.mysql:
    url: jdbc:mysql://localhost:3306/multiple_datasource_example
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  datasource.postgres:
      url: jdbc:postgresql://localhost:5432/multiple_datasource_example
      username: postgres
      password: igdefault
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
postgres:
  initialPoolSize: 20
  maxPoolSize: 50
  minPoolSize: 20
  acquireIncrement: 5
  maxIdleTime: 300
  properties:
      hibernate.hbm2ddl.auto: create-drop
      hibernate.current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      hibernate.implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy